
- name: Connect virtual networks with virtual network peering
  hosts: localhost
  connection: local

  tasks:

  - name: Initial vnet peering
    azure_rm_virtualnetworkpeering:
      state: absent
      resource_group: "{{ resource_group }}"
      name: "{{ peering_name }}"
      virtual_network: "{{ vnet_resouce_id_1 }}"
      remote_virtual_network:
        resource_group: "{{ resource_group_secondary }}"
        name: "{{ vnet_resouce_id_2 }}"
      allow_virtual_network_access: true
      allow_forwarded_traffic: false
      

  - name: Connect vnet peering
    azure_rm_virtualnetworkpeering:
      state: absent
      resource_group: "{{ resource_group_secondary }}"
      name: "{{ peering_name }}"
      virtual_network: "{{ vnet_resouce_id_2 }}"
      remote_virtual_network:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_resouce_id_1 }}"
      allow_virtual_network_access: true
      allow_forwarded_traffic: false

