---
- name: USE ACI REST MODULE
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE TENANT HAS L3 EXTERNAL NETWORK
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        method: "post"
        path: "api/mo/uni/tn-mentos/out-corp_l3/lnodep-my_node_profile.json"
        content: '{"totalCount":"1","imdata":[{"l3extLNodeP":{"attributes":{"annotation":"","configIssues":"","descr":"","dn":"uni/tn-mentos/out-corp_l3/lnodep-my_node_profile","name":"my_node_profile","nameAlias":"","ownerKey":"","ownerTag":"","tag":"yellow-green","targetDscp":"unspecified"}}}]}'

